### ISSUE TITLE
An issue while downloading

### ISSUE THREAD

**Issue by gpkgit** [bcbcbcbcbcl/working-coursera-download-with-selenium#1]
Traceback (most recent call last):
  File "D:\couresera_videos_sample\coursera-download.py", line 197, in <module>
    browser.find_element_by_xpath("(//nav)[2]/button").click()
  File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: (//nav)[2]/button

//I am new to things like this.If more info needed kindly intimate me,I'll definitely provide them.

**Comment by bcbcbcbcbcl** [comment]
This could be due to the HTML elements in Coursera website have been changed, I will update the script this weekend.

**Comment by bcbcbcbcbcl** [comment]
This could be due to some HTML elements in Coursera website have been changed, I will update the script this weekend.

**Comment by bcbcbcbcbcl** [comment]
Updated and tested the script, it should be working fine now. If you have WebDriverException issue, please download the latest geckodriver. I will close this issue for now, feel free to reopen if the problem persists.
